### ISSUE TITLE
Clojure Vs JavaScript

### ISSUE THREAD

**Issue by rarora4** [bighero4/MarkParser#17]
Understand the feasibility of using Clojure, if not select JavaScript as an alternative.

**Comment by yatish27** [comment]
Can we have multiple people working on the same issue? Can you assign it to me as well ?

**Comment by yatish27** [comment]
@rarora4 As a deliverable I am adding a docs folder which will contain all the research. We can also add a wiki page. What do you think which one would be better ?

**Comment by bhashwanth** [comment]
Finalized JavaScript for functional track
